name: Test
on: [pull_request]
jobs:
  cypress-run:
    name: Test My Movies
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch .env
          echo TMDB_API=${{ secrets.TMDB_API }} >> .env.local
          echo TMDB_API=${{ secrets.TMDB_API }} >> .env.local
          echo AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID }} >> .env.local
          echo AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }} >> .env.local
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run ci
          start: npm run start
          wait-on: 'http://localhost:3000'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: IgnusG/jest-report-action@v2.3.3
        if: always() # Or use "continue-on-error: true" in previous test step
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
